### ISSUE TITLE
Migrated bug: "memory error" reported by valsamo on 2007-03-08

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Sergey197806/sitemap-generators#2]
```
The original bug is listed here:
http://sourceforge.net/tracker/index.php?func=detail&aid=1676398&group_id=137793
&atid=739383

Hello,

I try to generate sitemap with access logs method.
When the script parses the log file, I take the errors as shown below:

Opened ACCESSLOG file: /home/[mysite]/logs/[logfile.gz]
Traceback (most recent call last):
File "sitemap_gen.py", line 2203, in ?
sitemap.Generate()
File "sitemap_gen.py", line 1775, in Generate
input.ProduceURLs(self.ConsumeURL)
File "sitemap_gen.py", line 1115, in ProduceURLs
for line in file.readlines():
File "/usr/local/lib/python2.4/gzip.py", line 414, in readlines
line = self.readline()
File "/usr/local/lib/python2.4/gzip.py", line 388, in readline
c = self.read(readsize)
File "/usr/local/lib/python2.4/gzip.py", line 225, in read
self._read(readsize)
File "/usr/local/lib/python2.4/gzip.py", line 277, in _read
uncompress = self.decompress.decompress(buf)
MemoryError

Can anyone help me with this?

thanks,
Soulis
```

Original issue reported on code.google.com by `api.ma...@gmail.com` on 13 Aug 2007 at 7:23

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
http://www.kaersen.com
```

Original comment by `kaer...@gmail.com` on 26 Mar 2009 at 5:47

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I have fixed sitemap_gen.py so it now does not consume enormous amount of 
memory and
python does not die with MemoryError. Look here
http://www.bashkirtsev.com/2009/05/14/sitemap/
```

Original comment by `vbashkir...@gmail.com` on 14 May 2009 at 3:47

**Comment by GoogleCodeExporter** [comment]
```
www.smh499.jeeran.com
```

Original comment by `smh...@gmail.com` on 29 Aug 2009 at 5:09

**Comment by GoogleCodeExporter** [comment]
```
www.mykk.net  深圳SEO
```

Original comment by `peng0272...@yahoo.com.cn` on 13 Sep 2010 at 6:53

**Comment by GoogleCodeExporter** [comment]
```
http://www.bestpropertyinfo.com
```

Original comment by `bpropert...@gmail.com` on 19 May 2011 at 8:56
